# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0bdb6e652aecffc097d7f88af91e2dbc3e843800289ebfbb9459444026c7e1163913f45483cad61e883c299762b5622eccd7a4eb56ab40f035f1124132be6d2

test:
  secret_key_base: 4fe49c66b76b92c2757b4ec905f2580cd3f6e38cce2e33aea8f5acb66d40166938ed0771a9b28bc7d2b5c3cf67d5a1250a4640ae29f71db82d48cee11e1f9b86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
